spring:
  jpa:
    show-sql: true  # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true  # SQL을 보기 좋게 출력
    defer-datasource-initialization: true  # JPA 초기화 후 data.sql 실행하도록 설정
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시 테이블 자동 생성 (필수)
  sql:
    init:
      mode: always  # data.sql 실행 활성화
#  datasource:
#    url: jdbc:h2:mem:testdb  # H2 인메모리 데이터베이스 설정 (URL 수정)
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 웹 콘솔 경로 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id # 스스로 세팅 필요
            client-secret: test-client-secret # 스스로 세팅 필요
            scope:
              - email
              - profile


jwt:
  issuer: ajufresh@gmail.com  # 스스로 세팅 필요
  secret_key: test_key  # 스스로 세팅 필요